### PR TITLE
Use a pcap wrapper instead of tcpdump

### PR DESCRIPTION
**Pull request by leoplo**
I did benchmarks to mesure the performance difference : 

```python
import timeit

setup = 'from struct import pack; from subprocess import Popen, PIPE'

code = '''
cmd = "tcpdump -ddd \\"ip proto not 2\\""
result = Popen(cmd, shell=True, stdout=PIPE)
bpf_filter = b''
tmp = result.stdout.read().splitlines()
num = tmp[0]
for line in tmp[1:]:
    bpf_filter += pack("HBBI", *tuple(map(int, line.split(b' '))))
'''

print(timeit.timeit(stmt=code, setup=setup, number=20))
```

16.16022198099745

```python
import timeit

setup = 'from pcap_wrapper import bpf'

code = '''
num, bpf_filter = bpf(b'ip proto not 2').compiled_filter()
'''

print(timeit.timeit(stmt=code, setup=setup, number=20))
```

0.00014773994917050004

### CODE REVIEW

**Comment by pedrofran12** [comment]
Hi @leoplo 

I tried today this PR and got some issues... not sure if there are dependencies missing (on requirements.txt).

I have tried installing pim_dm from your repo and it failed on both a docker container and directly on top of my PC OS.

I tried installing with:
```pip3 install setup.py```
since it now looks this is required before being able to run pim-dm due to the external module/extension defined on setup.py.

and got the following output:
```
pedro@pedro-Ubuntu:~/Desktop/github/pim_dm5/emulation/shared/root/pim_dm$ sudo pip3 install setup.py 
ERROR: Could not find a version that satisfies the requirement setup.py (from versions: none)
ERROR: No matching distribution found for setup.py
```

Is `pcap` defined on setup.py a dependecy that needs to be installed?

**Comment by leoplo** [comment]
Indeed [sources](https://github.com/pedrofran12/pim_dm/pull/10/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R25) needed to be a list. I retried both `python pip install .` and `python setup.py build_ext -i` (to generate a new pcap.c file with Cython) and it went well.

**Comment by pedrofran12** [comment]
Thank you for the update.

I will merge the PR :+1:

**Comment by pedrofran12** [comment]
If you want you can send an equivalent PR to [HPIM-DM](https://github.com/pedrofran12/hpim_dm) (the code structure is similar).

**Comment by pedrofran12** [comment]
Your PR broke the automatic publish of releases to PyPi :face_with_spiral_eyes:

It looks like some files that are now created cannot be uploaded to PyPi:
```
Binary wheel 'pim_dm-1.4.0-cp310-cp310-linux_x86_64.whl' has an        
         unsupported platform tag 'linux_x86_64'.    
```

The code is merged on master but need some weeks to understand how to fix the workflow and publish on PyPi.

**Comment by leoplo** [comment]
I see that until now `wheel` of pim-dm was release as `any` because it was pure Python. Now there is a C file generated by Cython so when building the `wheel` it creates a `.so` file which is platform dependent so your `wheel` is now `linux_x86_64.whl` instead of `any.whl`. That is probably what your CI did not appreciate.

**Comment by leoplo** [comment]
Here is a discussion on what happened: https://stackoverflow.com/questions/59451069/binary-wheel-cant-be-uploaded-on-pypi-using-twine

**Comment by leoplo** [comment]
Sorry I did not see that limitation coming :s

**Comment by leoplo** [comment]
While trying to create a pim-dm archive suitable for pypi with `python setup.py sdist` I realized that the generated archive does not contain [filter.h](filter.h) and because of that the egg is not installable. To fix it a [manifest](https://github.com/leoplo/pim_dm/commit/b8523a619c35161d1f71704b5cb37a7581178c7b) is required.

This also means that #13 can be reverted by adding `requirements.txt` to `MANIFEST.in` (as it is not how `requirements.txt` is supposed to used from documentation I will not push much in that direction though).

**Pull request merged**
